#!/usr/bin/env bash

# Bootstrap new CodeSpaces

# Configure Git to automatically create branches on the remote
# Skipping the error prompt to set an upstream branch
git config --global push.autoSetupRemote true
